#! /bin/sh
polybar &
xsetroot -cursor_name left_ptr &
sxhkd &
nitrogen --restore &
setxkbmap latam &
picom &
nm-applet &
dunst &
greenclip daemon


bspc monitor -d I II III IV V 

bspc config border_width         1
bspc config window_gap          12
bspc config top_padding 55
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a nautilus state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a chromium desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating

bspc config active_border_color \#512a56


